env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-1-release-amd64
      image: freebsd-11-3-release-amd64
  install_script:
    - sed -i.bak -e 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
    - cat /etc/pkg/FreeBSD.conf
    - pkg update
    - pkg upgrade -y
    - pkg install -y git cmake python bison autotools textproc/flex yara
  build_script:
    - ln -sf /usr/local/bin/python3.7 /usr/local/bin/python3
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
    - make -j2
